// user.types.js >>> types of functionality what you can do

const userTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_ERROR: "SIGN_IN_ERROR",
    SIGN_UP_ERROR: "SIGN_UP_ERROR",
    SIGN_UP_SUCCESS:"SIGN_UP_SUCCESS",
    PHONE_LOGIN_SUCCESS: "PHONE_LOGIN_SUCCESS",
    PHONE_LOGIN_ERROR:"PHONE_LOGIN_ERROR",
    RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_ERROR:"RESET_PASSWORD_ERROR",
    RESET_AUTH_FORMS:"RESET_AUTH_FORMS",
};

export default userTypes;
